name: Pull Request to Main

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

concurrency:
  group: pr-to-main-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  pull-requests: write
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v7

      # https://github.com/pnpm/action-setup
      - uses: pnpm/setup@v2
        with:
          version: 12
          runtime: node@24
          install: false

      - name: Install dependencies
        run: pnpm install

      - name: Run svelte check
        run: pnpm check

      - name: Build
        run: pnpm build
